version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: matching_development
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./server
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails ridge:apply && bundle exec rails db:seed && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./server:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=mysql2://root:password@db:3306/matching_development
      - JWT_SECRET=your_secure_jwt_secret_key_here
    depends_on:
      db:
        condition: service_healthy

  client:
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
      - NODE_ENV=development
    depends_on:
      - api
    command: ["sh", "-c", "npm install && npm run dev -- --host 0.0.0.0"]

volumes:
  mysql_data:
  bundle_cache:
