default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: matching_development

test:
  <<: *default
  database: matching_test

production:
  <<: *default
  database: matching_production
  username: <%= ENV['MATCHING_DATABASE_USER'] %>
  password: <%= ENV['MATCHING_DATABASE_PASSWORD'] %>
